'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import PeakGGWordmark from './PeakGGWordmark';
import {signOut} from '../../lib/auth/actions';

const links=[{number:'01',label:'PLAY',href:'/play'},{number:'02',label:'TEAMS',href:'/teams'},{number:'03',label:'RANKS',href:'/ranks'},{number:'04',label:'TOURNAMENTS',href:'/tournaments'}] as const;

export default function SiteHeader({user}:{user?:{username:string;avatarUrl?:string|null;isAdmin?:boolean}|null}){
  const path=usePathname();const[open,setOpen]=useState(false);const[account,setAccount]=useState(false);const[scrolled,setScrolled]=useState(false);const trigger=useRef<HTMLButtonElement>(null);const first=useRef<HTMLAnchorElement>(null);const accountRoot=useRef<HTMLDivElement>(null);
  useEffect(()=>{const update=()=>setScrolled(scrollY>24);update();addEventListener('scroll',update,{passive:true});return()=>removeEventListener('scroll',update)},[]);
  useEffect(()=>{const background=[document.querySelector('main'),document.querySelector('footer')].filter(Boolean) as HTMLElement[];const key=(event:KeyboardEvent)=>{if(event.key==='Escape'&&open){setOpen(false);trigger.current?.focus()}if(event.key==='Tab'&&open){const items=[...document.querySelectorAll<HTMLElement>('#mobile-menu a,#mobile-menu button')].filter(item=>item.tabIndex>=0),start=items[0],end=items.at(-1);if(event.shiftKey&&document.activeElement===start){event.preventDefault();end?.focus()}else if(!event.shiftKey&&document.activeElement===end){event.preventDefault();start?.focus()}}};addEventListener('keydown',key);document.body.classList.toggle('menu-open',open);background.forEach(element=>element.toggleAttribute('inert',open));if(open)setTimeout(()=>first.current?.focus(),0);return()=>{removeEventListener('keydown',key);document.body.classList.remove('menu-open');background.forEach(element=>element.removeAttribute('inert'))}},[open]);
  useEffect(()=>{if(!account)return;const dismiss=(event:PointerEvent)=>{if(!accountRoot.current?.contains(event.target as Node))setAccount(false)};const escape=(event:KeyboardEvent)=>{if(event.key==='Escape')setAccount(false)};addEventListener('pointerdown',dismiss);addEventListener('keydown',escape);return()=>{removeEventListener('pointerdown',dismiss);removeEventListener('keydown',escape)}},[account]);
  const active=(href:string)=>path===href||path.startsWith(`${href}/`);
  const closeNavigation=()=>{setOpen(false);setAccount(false)};
  const accountLinks=<><Link href="/dashboard" onClick={closeNavigation}>DASHBOARD</Link><Link href="/profile" onClick={closeNavigation}>PROFILE</Link><Link href="/settings" onClick={closeNavigation}>SETTINGS</Link>{user?.isAdmin&&<Link href="/admin" onClick={closeNavigation}>CONTROL ROOM</Link>}<form action={signOut}><button type="submit">SIGN OUT</button></form></>;
  return <header className={`site-header ${scrolled?'is-scrolled':''}`}><div className="site-nav"><div className="site-nav-brand"><PeakGGWordmark/></div><nav aria-label="Primary navigation">{links.map(item=><Link key={item.href} href={item.href} aria-current={active(item.href)?'page':undefined}><small>{item.number}</small><span>{item.label}</span>{active(item.href)&&<i className="nav-active-slash" aria-hidden="true"/>}</Link>)}</nav><div className="site-nav-right"><span>EU / CEST</span>{user?<div className="account-nav" ref={accountRoot}><button type="button" aria-expanded={account} aria-controls="account-menu" onClick={()=>setAccount(value=>!value)}><span className="account-avatar" aria-hidden="true">{user.username.slice(0,1).toUpperCase()}</span>{user.username}</button>{account&&<div id="account-menu">{accountLinks}</div>}</div>:<Link className="nav-enter" href="/login">ENTER <b aria-hidden="true">↗</b></Link>}</div><button ref={trigger} className="mobile-menu-trigger" type="button" aria-label={open?'Close navigation menu':'Open navigation menu'} aria-expanded={open} aria-controls="mobile-menu" onClick={()=>setOpen(value=>!value)}>{open?'CLOSE ×':'MENU +'}</button></div><div id="mobile-menu" className={`mobile-menu ${open?'is-open':''}`} role="dialog" aria-modal="true" aria-label="Navigation menu" aria-hidden={!open}><div className="mobile-menu-top"><PeakGGWordmark/><button type="button" aria-label="Close navigation menu" onClick={()=>{setOpen(false);trigger.current?.focus()}}>CLOSE ×</button></div><nav aria-label="Mobile navigation">{links.map((item,index)=><Link ref={index===0?first:undefined} tabIndex={open?0:-1} key={item.href} href={item.href} aria-current={active(item.href)?'page':undefined} onClick={closeNavigation}><small>{item.number}</small><span>{item.label}</span></Link>)}</nav>{user&&<div className="mobile-account">{accountLinks}</div>}<div className="mobile-menu-footer"><p>EUROPE / SEASON 01</p><div>{process.env.NEXT_PUBLIC_DISCORD_URL&&<a tabIndex={open?0:-1} href={process.env.NEXT_PUBLIC_DISCORD_URL}>DISCORD</a>}<span>CONTACT</span></div><p>© 2026 PEAKGG</p></div></div></header>;
}
