'use client';
import Image from 'next/image';
import {useRef,useState} from 'react';
const roles=[
  {role:'DUELIST',agent:'Jett',protocol:'Entry / Pressure',playstyle:'Aggressive',image:'/assets/agents/jett.png',position:'52% 45%'},
  {role:'CONTROLLER',agent:'Omen',protocol:'Space / Tempo',playstyle:'Measured',image:'/assets/agents/omen.png',position:'48% 45%'},
  {role:'INITIATOR',agent:'Fade',protocol:'Info / Opening',playstyle:'Proactive',image:'/assets/agents/fade.png',position:'50% 44%'},
  {role:'SENTINEL',agent:'Killjoy',protocol:'Anchor / Hold',playstyle:'Calculated',image:'/assets/agents/killjoy.png',position:'50% 43%'},
  {role:'FLEX',agent:'Yoru',protocol:'Adapt / Complete',playstyle:'Unpredictable',image:'/assets/agents/yoru.png',position:'50% 44%'},
];
export default function Squad(){const [active,setActive]=useState(0);const tabs=useRef<Array<HTMLButtonElement|null>>([]);const selected=roles[active];const select=(index:number,focus=false)=>{const next=(index+roles.length)%roles.length;setActive(next);if(focus)requestAnimationFrame(()=>tabs.current[next]?.focus())};const onKeyDown=(event:React.KeyboardEvent,index:number)=>{if(event.key==='ArrowRight'||event.key==='ArrowDown'){event.preventDefault();select(index+1,true)}else if(event.key==='ArrowLeft'||event.key==='ArrowUp'){event.preventDefault();select(index-1,true)}else if(event.key==='Home'){event.preventDefault();select(0,true)}else if(event.key==='End'){event.preventDefault();select(roles.length-1,true)}};return <section className="dossier section" id="squad"><header className="dossier-head"><div><div className="kicker">04 / BUILD YOUR SQUAD</div><h2>FIND YOUR <span>FIVE.</span></h2></div><p>Five roles. One roster. Select a protocol to inspect the player profile your squad needs.</p></header><div className="dossier-tabs" role="tablist" aria-label="Competitive roles">{roles.map((item,i)=><button ref={node=>{tabs.current[i]=node}} tabIndex={active===i?0:-1} key={item.role} role="tab" aria-selected={active===i} aria-controls="role-dossier" onKeyDown={event=>onKeyDown(event,i)} onClick={()=>select(i)}><small>0{i+1}</small><span>{item.role}</span><b>{item.agent}</b></button>)}</div><div className={`dossier-stage role-${active+1}`} id="role-dossier" role="tabpanel" aria-live="polite"><aside><b>#00{active+1}</b><dl><div><dt>ROLE</dt><dd>{selected.role}</dd></div><div><dt>AGENT</dt><dd>{selected.agent}</dd></div><div><dt>PROTOCOL</dt><dd>{selected.protocol}</dd></div><div><dt>PLAYSTYLE</dt><dd>{selected.playstyle}</dd></div></dl></aside><div className="dossier-visual"><strong aria-hidden="true">{selected.role}</strong><Image className="agent-ghost" src={selected.image} alt="" fill sizes="(max-width: 700px) 100vw, 70vw" style={{objectPosition:selected.position}}/><Image key={selected.image} className="agent-main" src={selected.image} alt={`${selected.agent}, ${selected.role} agent`} fill sizes="(max-width: 700px) 100vw, 70vw" priority={active===0} style={{objectPosition:selected.position}}/><div className="dossier-scan"/></div><div className="dossier-tag"><span>ROLE PROTOCOL</span><b>{selected.agent}</b></div><div className="dossier-mobile-controls"><button aria-label="Previous role" onClick={()=>select(active-1)}><span aria-hidden="true">←</span></button><span><b>0{active+1}</b> / 05</span><button aria-label="Next role" onClick={()=>select(active+1)}><span aria-hidden="true">→</span></button></div></div></section>}
