'use client';
import {useEffect,useRef} from 'react';
import type {TournamentFilters as Values,TournamentTab} from '@/data/tournaments';
const tabs:[TournamentTab,string][]=[['ALL','ALL 06'],['OPEN','OPEN 02'],['LIVE','LIVE 00'],['UPCOMING','UPCOMING 04'],['LEAGUES','LEAGUES 01'],['SPECIAL','SPECIAL 01']];
const selects:[keyof Pick<Values,'region'|'format'|'teamSize'>,string,readonly string[]][]=[['region','REGION',['ALL','EUROPE']],['format','FORMAT',['ALL','5V5','1V1']],['teamSize','TEAM SIZE',['ALL','16','32','64']]];

export default function TournamentFilters({values,panel,onTab,onChange,onToggle,onClose}:{values:Values;panel:boolean;onTab:(tab:TournamentTab)=>void;onChange:<K extends keyof Values>(key:K,value:Values[K])=>void;onToggle:()=>void;onClose:()=>void}){
  const trigger=useRef<HTMLButtonElement>(null);const close=useRef<HTMLButtonElement>(null);
  useEffect(()=>{if(!panel)return;document.body.classList.add('filters-open');close.current?.focus();const onKey=(event:KeyboardEvent)=>{if(event.key==='Escape'){onClose();trigger.current?.focus()}};addEventListener('keydown',onKey);return()=>{removeEventListener('keydown',onKey);document.body.classList.remove('filters-open')}},[panel,onClose]);
  const controls=(mobile=false)=><>{selects.map(([key,label,options])=><label key={`${mobile?'mobile':'desktop'}-${key}`}><span>{label}</span><select name={key} aria-label={label} value={values[key]} onChange={event=>onChange(key,event.target.value as Values[typeof key])}>{options.map(option=><option key={option}>{option}</option>)}</select></label>)}</>;
  const dismiss=()=>{onClose();trigger.current?.focus()};
  return <div className="t-controls" id="event-filters"><div className="t-wrap t-controls-inner"><nav className="t-tabs" aria-label="Tournament categories">{tabs.map(([value,label])=><button type="button" key={value} aria-pressed={values.tab===value} onClick={()=>onTab(value)}>{label}</button>)}</nav><div className="t-selects">{controls()}</div><button ref={trigger} className="t-filter-toggle" type="button" aria-expanded={panel} aria-controls="mobile-filter-panel" onClick={onToggle}>FILTERS <span>{Object.values(values).filter(value=>value!=='ALL').length||''}</span></button></div>{panel&&<><button className="t-filter-backdrop" type="button" aria-label="Close filters" onClick={dismiss}/><div className="t-mobile-panel" id="mobile-filter-panel" role="dialog" aria-modal="true" aria-labelledby="mobile-filter-title"><div className="t-mobile-panel-head"><p id="mobile-filter-title">FILTER EVENTS</p><button ref={close} type="button" onClick={dismiss} aria-label="Close filters">CLOSE ×</button></div><div className="t-wrap">{controls(true)}</div><button className="t-filter-apply" type="button" onClick={dismiss}>SHOW EVENTS</button></div></>}</div>;
}
