'use server';
import {redirect} from 'next/navigation';
import {createClient} from '../supabase/server';

const safeNext=(value:FormDataEntryValue|null,fallback:string)=>typeof value==='string'&&value.startsWith('/')&&!value.startsWith('//')?value:fallback;
export async function signIn(form:FormData){const supabase=await createClient();const email=String(form.get('email')||'').trim();const password=String(form.get('password')||'');const {error}=await supabase.auth.signInWithPassword({email,password});if(error)redirect(`/login?error=${encodeURIComponent(error.message)}&next=${encodeURIComponent(safeNext(form.get('next'),'/dashboard'))}`);redirect(safeNext(form.get('next'),'/dashboard'))}
export async function register(form:FormData){const supabase=await createClient();const email=String(form.get('email')||'').trim();const password=String(form.get('password')||'');const confirmation=String(form.get('confirmation')||'');if(password!==confirmation)redirect('/register?error=Passwords%20do%20not%20match');const {error}=await supabase.auth.signUp({email,password});if(error)redirect(`/register?error=${encodeURIComponent(error.message)}`);redirect('/onboarding')}
export async function requestPasswordReset(form:FormData){const supabase=await createClient();const email=String(form.get('email')||'').trim();const origin=process.env.NEXT_PUBLIC_SITE_URL||'http://localhost:3000';const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${origin}/forgot-password?reset=1`});if(error)redirect(`/forgot-password?error=${encodeURIComponent(error.message)}`);redirect('/forgot-password?sent=1')}
export async function updatePassword(form:FormData){const supabase=await createClient();const password=String(form.get('password')||'');const {error}=await supabase.auth.updateUser({password});if(error)redirect(`/forgot-password?reset=1&error=${encodeURIComponent(error.message)}`);redirect('/dashboard')}
export async function signOut(){const supabase=await createClient();await supabase.auth.signOut();redirect('/')}
